services:
  server: # turn it last
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
      - ./logs:/var/log/nginx
    depends_on:
      - user-api
      - minio
  minio: # run and setup first for all api
    image: minio/minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_REGION=us-east-1
    command: server --console-address ":9001" /data
  redis: # turn it first for all api
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
  user-api: # turn it after userdb and wait until it done then open terminal connect adb with phone
    build:
      context: .
      dockerfile: Dockerfile-UserModule
    depends_on:
      - userdb
      - minio
      - redis
    volumes:
      - ./user-module/:/var/www
  userdb: # turn it and wait until it done before turn user-api
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
#    ports:
#      - "3306:3306"
#    volumes:
#      - userdb:/var/lib/mysql



