FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends\
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zlib1g-dev \
    libzip-dev \
    libpq-dev \
    zip \
    unzip

# Install PHP extensions
RUN apt-get install -y --no-install-recommends libmagickwand-dev
RUN pecl install imagick
RUN docker-php-ext-enable imagick
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install pdo pdo_pgsql pgsql mbstring exif pcntl bcmath gd zip

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www
COPY room-test-module /var/www/

RUN apt install -y --no-install-recommends python3-pip
RUN pip install pandas psycopg2-binary sqlalchemy --break-system-packages

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["bash", "docker-entrypoint.sh"]
