services:
  server: # turn it last
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
      - ./logs:/var/log/nginx
    depends_on:
      - user-api
      - room-test-api
      - minio
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_REGION=us-east-1
    command: server --console-address ":9001" /data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
  user-api:
    build:
      context: .
      dockerfile: Dockerfile-UserModule
    depends_on:
      - userdb
      - minio
      - redis
    volumes:
      - ./user-module/:/var/www
      - /var/www/vendor
  room-test-api:
    build:
      context: .
      dockerfile: Dockerfile-RoomModule
    depends_on:
      - room-test-db
      - minio
      - redis
    volumes:
      - ./room-test-module/:/var/www
      - /var/www/vendor
  userdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-db
      TZ: Asia/Ho_Chi_Minh
  #    volumes:
  #      - user-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  paper-test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paper-test-db
      TZ: Asia/Ho_Chi_Minh
    #    volumes:
    #      - paper-test-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  room-test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: room-test-db
      TZ: Asia/Ho_Chi_Minh
#    volumes:
    #      - room-test-db:/var/lib/postgresql/data
    ports:
      - "5434:5432"


